name: paddle_env
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - attrs=23.1.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - colorama=0.4.6
  - comm=0.1.2
  - cryptography=41.0.7
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - executing=0.8.3
  - icu=73.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.1.1
  - ipykernel=6.25.0
  - ipython=8.12.2
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - json5=0.9.6
  - jsonschema=4.19.2
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.8
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.25.1
  - jupyterlab_widgets=3.0.9
  - krb5=1.20.1
  - leptonica=1.83.1
  - lerc=4.0.0
  - libarchive=3.7.2
  - libclang13=14.0.6
  - libdeflate=1.19
  - libffi=3.4.4
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libpng=1.6.39
  - libpq=12.15
  - libsodium=1.0.18
  - libtiff=4.6.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.12.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.6
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - openjpeg=2.5.0
  - openssl=3.2.1
  - overrides=7.4.0
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - pytz=2023.3.post1
  - pywin32=305
  - pywinpty=2.0.10
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - send2trash=1.8.2
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.7.1
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.1.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.2.0
      - astor==0.8.1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrdict==2.0.1
      - attrdict3==2.0.2
      - babel==2.14.0
      - bce-python-sdk==0.8.98
      - blinker==1.7.0
      - boto3==1.34.39
      - botocore==1.34.39
      - cachetools==5.3.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorlog==6.8.0
      - contourpy==1.1.1
      - cssselect==1.2.0
      - cssutils==2.9.0
      - cycler==0.12.1
      - cython==3.0.7
      - datasets==2.16.0
      - dill==0.3.4
      - easyocr==1.7.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.0
      - fastapi==0.108.0
      - filelock==3.13.1
      - fire==0.5.0
      - flask==3.0.0
      - flask-babel==4.0.0
      - flatbuffers==24.3.7
      - fonttools==4.47.0
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - future==0.18.3
      - gast==0.4.0
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.62.1
      - h11==0.14.0
      - h5py==3.10.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.1
      - idna==3.6
      - imageio==2.33.1
      - imgaug==0.4.0
      - itsdangerous==2.1.2
      - jieba==0.42.1
      - jmespath==1.0.1
      - joblib==1.3.2
      - keras==2.13.1
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - libclang==18.1.1
      - lmdb==1.4.1
      - lxml==4.9.4
      - markdown==3.6
      - markdown-it-py==3.0.0
      - matplotlib==3.7.4
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.12.2
      - networkx==3.1
      - ninja==1.11.1.1
      - numpy==1.24.3
      - oauthlib==3.2.2
      - onnx==1.15.0
      - opencv-contrib-python==4.6.0.66
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.9.0.80
      - openpyxl==3.1.2
      - opt-einsum==3.3.0
      - packaging==23.2
      - paddle2onnx==1.0.6
      - paddlefsl==1.1.0
      - paddlenlp==2.6.1
      - paddleocr==2.7.0.3
      - paddlepaddle==2.6.0
      - pandas==2.0.3
      - pdf2docx==0.5.6
      - pillow==10.1.0
      - premailer==3.10.0
      - protobuf==4.25.3
      - psutil==5.9.7
      - py-cpuinfo==9.0.0
      - pyarrow==14.0.2
      - pyarrow-hotfix==0.6
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyclipper==1.3.0.post5
      - pycryptodome==3.19.1
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pygments==2.17.2
      - pymupdf==1.20.2
      - pypandoc==1.12
      - pyparsing==3.1.1
      - pytesseract==0.3.10
      - python-bidi==0.4.2
      - python-docx==1.1.0
      - pywavelets==1.4.1
      - rapidfuzz==3.6.0
      - rarfile==4.1
      - requests-oauthlib==1.4.0
      - rich==13.7.0
      - rsa==4.9
      - s3transfer==0.10.0
      - safetensors==0.4.1
      - scikit-image==0.21.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - sentencepiece==0.1.99
      - seqeval==1.2.2
      - shapely==2.0.2
      - starlette==0.32.0.post1
      - sympy==1.12
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-intel==2.13.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.4.0
      - tesseract==0.1.3
      - thop==0.1.1-2209072238
      - threadpoolctl==3.2.0
      - tifffile==2023.7.10
      - torch==1.11.0
      - torchaudio==0.11.0
      - torchvision==0.12.0
      - tqdm==4.66.1
      - typer==0.9.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - ultralytics==8.1.29
      - urllib3==2.1.0
      - uvicorn==0.25.0
      - visualdl==2.5.3
      - werkzeug==3.0.1
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yacs==0.1.8
      - yarl==1.9.4
